name: Build Test and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm Dependencies
      run: npm install
    - name: Change the config
      run: echo "export const settings = { host:\"http://localhost:8083\" }"
    - name: Start Server
      run: npm run start &
    - name: Display SoftUni Username
      run: echo "murkata86"
    - name: Start the Unit tests
      run: npm run test:unit
    - name: Instal Playwright install
      run: npx playwright install
    - name: Start the UI tests
      run: npm run test:ui

  Deploy_App:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build_and_test
    steps:
      - name: Deploy backend
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.Backend_Key }}
          api-key: ${{ secrets.Render_API_Key }}



